"""Chunks API: buckets.

bucket = one corpus.parquet + its answers.parquet (the gabarito) + one
retriever. Create it, upload into it, search it at /api/buckets/{id}/search,
read its gabarito at /api/buckets/{id}/answers. To compare retrievers, make two
buckets from the same pair of files.

retriever kinds: bm25 (in-RAM index), vector (pgvector cosine), hybrid
(bm25 + vector, fused by Reciprocal Rank Fusion). Any of them can be reranked
per search (`?rerank=<reranker>`): retrieve top-RERANK_DEPTH, rescore with a
cross-encoder, cut to k. And the query itself can be rewritten per search
(`?variants=N`): N alternative phrasings, pre-generated by Claude into
rewrites.json (gen_rewrites.py), are each searched and the rankings fused by RRF.

Two kinds of bucket. `chunks`: the chunker's bucket.zip, as above.
`descriptions`: a description.parquet (filename, description — one summary per
document) + its own retriever, uploaded separately. A chunks search can take
one as its first layer (`?docs=<descriptions bucket>`): rank the descriptions,
keep the top doc_top documents, search only their chunks. Like ?rerank=, it is
a search option: any chunks bucket can use any descriptions bucket that covers
its files, and nothing is reindexed.

/api/search keeps the response shape of week01/week03 so `eval/` runs
unchanged; without `bucket=` it uses the most recently indexed bucket.
"""

import functools
import hashlib
import io
import itertools
import json
import os
import re
import threading
import time
import unicodedata
import uuid
import zipfile
from contextlib import contextmanager

import pandas as pd
import psycopg2
import Stemmer
import psycopg2.extras
from fastapi import BackgroundTasks, FastAPI, File, Form, HTTPException, Query, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from pgvector.psycopg2 import register_vector
from psycopg2.extras import Json, execute_values
from pydantic import BaseModel

DATABASE_URL = os.environ["DATABASE_URL"]
BATCH = 16  # small enough that embedded_count moves every minute or two on CPU

# One line per retriever. e5 wants its role prefixes or the vectors land in the
# wrong region of the space.
RETRIEVERS = {
    "minilm": {"kind": "vector", "model": "sentence-transformers/all-MiniLM-L6-v2",
               "dim": 384, "passage": "", "query": ""},
    "e5-base": {"kind": "vector", "model": "intfloat/multilingual-e5-base",
                "dim": 768, "passage": "passage: ", "query": "query: "},
    "e5-large": {"kind": "vector", "model": "intfloat/multilingual-e5-large",
                 "dim": 1024, "passage": "passage: ", "query": "query: "},
    # bge-m3: symmetric, no prefixes. Qwen3: instruction on the query side only,
    # last-token pooling comes from the model config via sentence-transformers.
    "bge-m3": {"kind": "vector", "model": "BAAI/bge-m3", "dim": 1024, "passage": "", "query": ""},
    "qwen3-0.6b": {"kind": "vector", "model": "Qwen/Qwen3-Embedding-0.6B", "dim": 1024, "passage": "",
                   "query": "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery: "},
    "bm25": {"kind": "bm25", "model": f"rank-bm25 (BM25{os.environ.get('BM25_VARIANT', 'Okapi')})"},
}
# hybrid-<model>: BM25 top-N and vector top-N fused by Reciprocal Rank Fusion.
# Rank-based, so BM25's unbounded scores and cosine never need normalising.
RETRIEVERS |= {f"hybrid-{n}": {"kind": "hybrid", "vector": n, "model": f"RRF(bm25 + {s['model']})"}
               for n, s in list(RETRIEVERS.items()) if s["kind"] == "vector"}
# Optional second stage, chosen per search (?rerank=): the bucket's retriever
# fetches RERANK_DEPTH candidates, a cross-encoder reads (query, chunk) together
# and reorders them. Nothing is indexed for it, so any bucket can use any reranker.
# CPU in Docker runs ~280 GFLOPS: 30 × 512-token pairs take ~45 s on bge, ~60 s
# on mxbai. mMiniLM (mMARCO, has Portuguese) is the one to iterate with.
RERANKERS = {
    "mminilm-rerank": "cross-encoder/mmarco-mMiniLMv2-L12-H384-v1",
    "bge-reranker": "BAAI/bge-reranker-v2-m3",
    "mxbai-rerank": "mixedbread-ai/mxbai-rerank-base-v2",
}
# Tuning knobs, read once at startup: change them in docker-compose and
# recreate the container, then re-run eval. Defaults are the textbook values.
BM25_VARIANT = os.environ.get("BM25_VARIANT", "Okapi")    # Okapi | Plus | L
BM25_K1 = float(os.environ.get("BM25_K1", "1.5"))         # term-frequency saturation
BM25_B = float(os.environ.get("BM25_B", "0.75"))          # chunk-length penalty
RRF_K = int(os.environ.get("RRF_K", "60"))                # Cormack et al. 2009
RRF_DEPTH = int(os.environ.get("RRF_DEPTH", "50"))        # candidates per ranker before fusing
RRF_BM25_WEIGHT = float(os.environ.get("RRF_BM25_WEIGHT", "1.0"))  # vector side is 1.0
RERANK_DEPTH = int(os.environ.get("RERANK_DEPTH", "30"))  # candidates the cross-encoder rescores
DOC_TOP = int(os.environ.get("DOC_TOP", "5"))             # layer 1: documents whose chunks layer 2 searches
# Query transformation (?variants=N): rewrites pre-generated by gen_rewrites.py, question -> [5 rewrites].
_rw_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "rewrites.json")
_rw = json.load(open(_rw_path, encoding="utf-8")) if os.path.exists(_rw_path) else {"model": None, "questions": []}
REWRITES = {r["question"]: r["rewrites"] for r in _rw["questions"]}
TRANSFORM_MODEL = _rw["model"]
MAX_VARIANTS = 5
REQUIRED_COLUMNS = {"chunk_id", "filename", "chunk_index", "pages", "text"}
ANSWER_COLUMNS = {"query_id", "chunk_id"}
DESCRIPTION_COLUMNS = {"filename", "description"}

_embedders: dict[str, object] = {}
_rerankers: dict[str, object] = {}
_embed_lock = threading.Lock()
_bm25: dict[tuple, tuple] = {}  # (bucket_id, docs?) -> (BM25 index, [id], [filename], {acronym: expansion})


# ── infra ──────────────────────────────────────────────────────────────────

@contextmanager
def db():
    conn = psycopg2.connect(DATABASE_URL)
    try:
        register_vector(conn)
        yield conn
    finally:
        conn.close()


def cursor(conn):
    return conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)


def wait_for_db(retries: int = 15, delay: int = 2) -> None:
    for attempt in range(1, retries + 1):
        try:
            psycopg2.connect(DATABASE_URL).close()
            return
        except psycopg2.OperationalError:
            print(f"DB not ready (attempt {attempt}/{retries})")
            time.sleep(delay)


def init_schema() -> None:
    raw = psycopg2.connect(DATABASE_URL)
    with raw, raw.cursor() as cur:
        cur.execute("CREATE EXTENSION IF NOT EXISTS vector")
    raw.close()
    with db() as conn, conn.cursor() as cur:
        # A pgdata volume from an earlier layout (corpora/indexes, chunks.corpus_id)
        # would survive CREATE IF NOT EXISTS. Nothing there is worth keeping: drop it.
        cur.execute("""
            DO $$ BEGIN
              IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'chunks')
                 AND NOT EXISTS (SELECT 1 FROM information_schema.columns
                                 WHERE table_name = 'chunks' AND column_name = 'bucket_id') THEN
                DROP TABLE IF EXISTS vectors, chunks, indexes, corpora CASCADE;
              END IF;
            END $$;
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS buckets (
                id             TEXT PRIMARY KEY,
                name           TEXT NOT NULL,
                created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                retriever      TEXT,
                status         TEXT NOT NULL DEFAULT 'empty',   -- empty | indexing | ready | error
                chunk_count    INTEGER NOT NULL DEFAULT 0,
                embedded_count INTEGER NOT NULL DEFAULT 0,
                parquet_sha    TEXT,
                error          TEXT,
                indexed_at     TIMESTAMPTZ
            );
            -- the chunker config from manifest.json, when imported as a zip
            ALTER TABLE buckets ADD COLUMN IF NOT EXISTS chunker JSONB;
            ALTER TABLE buckets ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'chunks';  -- chunks | descriptions
            -- VECTOR without a dimension: buckets with 384d and 768d models share
            -- the table. Exact scan filtered by bucket_id; ponytail: HNSW per dim
            -- if a bucket grows 100x.
            CREATE TABLE IF NOT EXISTS chunks (
                bucket_id   TEXT NOT NULL REFERENCES buckets(id) ON DELETE CASCADE,
                chunk_id    TEXT NOT NULL,
                filename    TEXT NOT NULL,
                chunk_index INTEGER NOT NULL,
                pages       JSONB,
                heading     TEXT,
                text        TEXT NOT NULL,
                embedding   VECTOR,
                PRIMARY KEY (bucket_id, chunk_id)
            );
            -- The gabarito travels with the corpus it was resolved against: a
            -- chunk_id only means something inside its own bucket.
            CREATE TABLE IF NOT EXISTS qrels (
                bucket_id TEXT NOT NULL REFERENCES buckets(id) ON DELETE CASCADE,
                query_id  TEXT NOT NULL,
                chunk_id  TEXT NOT NULL,
                part      INTEGER NOT NULL DEFAULT 0,
                coverage  REAL,
                PRIMARY KEY (bucket_id, query_id, chunk_id, part)
            );
            -- a descriptions bucket's rows: layer 1 of the two-layer search
            CREATE TABLE IF NOT EXISTS documents (
                bucket_id   TEXT NOT NULL REFERENCES buckets(id) ON DELETE CASCADE,
                filename    TEXT NOT NULL,
                description TEXT NOT NULL,
                embedding   VECTOR,
                PRIMARY KEY (bucket_id, filename)
            );
        """)
        # A background embedding dies with the process (restart, --reload). Its
        # bucket would otherwise sit at 'indexing' forever with no way to retry.
        cur.execute("""
            UPDATE buckets SET status = 'error', error = 'indexing interrupted by API restart — upload again'
            WHERE status = 'indexing'
        """)
        conn.commit()


def vector_name(retriever: str) -> str:
    """The vector model behind a retriever: itself, or the one a hybrid wraps."""
    return RETRIEVERS[retriever].get("vector", retriever)


def embedder(name: str):
    name = vector_name(name)
    with _embed_lock:
        if name not in _embedders:
            import torch
            from sentence_transformers import SentenceTransformer
            print(f"Loading {RETRIEVERS[name]['model']}…")
            # Force fp32: checkpoints saved in bf16 (Qwen3) would otherwise run
            # bf16 matmuls on CPU, which has no fast kernel here — 50x slower.
            _embedders[name] = SentenceTransformer(
                RETRIEVERS[name]["model"], model_kwargs={"torch_dtype": torch.float32}
            )
        return _embedders[name]


def reranker(name: str):
    with _embed_lock:
        if name not in _rerankers:
            import torch
            from sentence_transformers import CrossEncoder
            print(f"Loading {RERANKERS[name]}…")
            # 512 tokens covers a chunk plus the question; longer only costs CPU.
            _rerankers[name] = CrossEncoder(
                RERANKERS[name], max_length=512, model_kwargs={"torch_dtype": torch.float32}
            )
        return _rerankers[name]


_stemmer = Stemmer.Stemmer("portuguese")
# Numbers joined by / or - stay one token ("8666/93", "12/03/2020"), so exact
# references don't dissolve into "8", "666", "93". Thousand-separator dots
# go first, so "8.666" == "8666"; other dots still split words.
TOKEN_RE = re.compile(r"\d+(?:[/-]\d+)+|\w+")
DIGIT_DOT_RE = re.compile(r"(?<=\d)\.(?=\d)")


def strip_accents(text: str) -> str:
    return "".join(c for c in unicodedata.normalize("NFD", text) if not unicodedata.combining(c))


def tokenize(text: str) -> list[str]:
    # Stem, strip accents, stem again: Snowball's rules need accents, but the
    # second pass folds what's left so "decisão", "decisões" and "decisao" meet.
    # ponytail: a few pairs still split (notificação→notific, notificacao→notificac).
    words = _stemmer.stemWords(TOKEN_RE.findall(DIGIT_DOT_RE.sub("", text.lower())))
    return _stemmer.stemWords([strip_accents(w) for w in words])


ACRONYM_RE = re.compile(r"\(([A-ZÀ-Ý]{2,10})\)")
CONNECTORS = {"de", "da", "do", "das", "dos", "e", "em", "para", "a", "o", "of", "the", "and"}


def mine_acronyms(texts: list[str]) -> dict[str, list[str]]:
    """{acronym token: expansion tokens} from "Junta Administrativa de Recursos (JAR)".

    Walks back from each "(SIGLA)" matching initials of non-connector words.
    First definition wins; a sigla with no matching words is ignored."""
    found: dict[str, list[str]] = {}
    for text in texts:
        for m in ACRONYM_RE.finditer(text):
            sigla = strip_accents(m.group(1))
            words = re.findall(r"\w+", text[max(0, m.start() - 200):m.start()])
            initials, start = "", len(words)
            for i in range(len(words) - 1, -1, -1):
                if words[i].lower() in CONNECTORS:
                    continue
                initials = strip_accents(words[i][0]).upper() + initials
                if not sigla.endswith(initials):
                    break
                if initials == sigla:
                    start = i
                    break
            key = tokenize(sigla)
            if initials == sigla and len(key) == 1 and key[0] not in found.keys() | CONNECTORS:
                found[key[0]] = tokenize(" ".join(words[start:]))
    return found


def expand_query(tokens: list[str], acronyms: dict[str, list[str]]) -> list[str]:
    """Acronym in the query -> add its expansion; full expansion -> add the acronym."""
    extra = [t for tok in tokens for t in acronyms.get(tok, [])]
    extra += [a for a, exp in acronyms.items() if a not in tokens and set(exp) <= set(tokens)]
    return tokens + extra


app = FastAPI(on_startup=[wait_for_db, init_schema])
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])


# ── buckets ────────────────────────────────────────────────────────────────

class NewBucket(BaseModel):
    name: str


BUCKET_SQL = """
    SELECT b.*,
           (SELECT COUNT(*)::int FROM qrels q WHERE q.bucket_id = b.id) AS qrels_count,
           (SELECT COUNT(DISTINCT query_id)::int FROM qrels q WHERE q.bucket_id = b.id) AS queries_count,
           (SELECT COUNT(*)::int FROM documents d WHERE d.bucket_id = b.id) AS doc_count
    FROM buckets b
"""


def present(b: dict) -> dict:
    return {**b, "search_url": f"/api/buckets/{b['id']}/search",
            "answers_url": f"/api/buckets/{b['id']}/answers"}


def get_bucket(cur, bid: str) -> dict:
    cur.execute(BUCKET_SQL + " WHERE b.id = %s", (bid,))
    b = cur.fetchone()
    if not b:
        raise HTTPException(404, "bucket not found")
    return b


def read_parquet(upload_bytes: bytes, what: str, required: set[str]):
    try:
        df = pd.read_parquet(io.BytesIO(upload_bytes))
    except Exception as e:
        raise HTTPException(400, f"{what}: not a readable parquet: {e}")
    missing = required - set(df.columns)
    if missing:
        raise HTTPException(400, f"{what}: missing columns {sorted(missing)}")
    return df


@app.get("/api/buckets")
def list_buckets():
    with db() as conn, cursor(conn) as cur:
        cur.execute(BUCKET_SQL + " ORDER BY b.created_at DESC")
        return [present(b) for b in cur.fetchall()]


@app.post("/api/buckets", status_code=201)
def create_bucket(body: NewBucket):
    name = body.name.strip()
    if not name:
        raise HTTPException(400, "name is required")
    with db() as conn, cursor(conn) as cur:
        cur.execute("INSERT INTO buckets (id, name) VALUES (%s, %s) RETURNING id",
                    (uuid.uuid4().hex[:8], name))
        bid = cur.fetchone()["id"]
        conn.commit()
        return present(get_bucket(cur, bid))


@app.get("/api/buckets/{bid}")
def read_bucket(bid: str):
    with db() as conn, cursor(conn) as cur:
        return present(get_bucket(cur, bid))


@app.delete("/api/buckets/{bid}", status_code=204)
def delete_bucket(bid: str):
    forget_bm25(bid)
    with db() as conn, conn.cursor() as cur:
        cur.execute("DELETE FROM buckets WHERE id = %s", (bid,))
        if cur.rowcount == 0:
            raise HTTPException(404, "bucket not found")
        conn.commit()


# ── upload + indexing ──────────────────────────────────────────────────────

def write_vectors(cur, table: str, key: str, bid: str, batch: list[tuple], vecs) -> None:
    # execute_values allows exactly one %s, so bucket_id rides inside each row.
    execute_values(
        cur,
        f"UPDATE {table} SET embedding = v.emb::vector FROM (VALUES %s) AS v(bid, id, emb) "
        f"WHERE {table}.bucket_id = v.bid AND {table}.{key} = v.id",
        [(bid, i, v.tolist()) for (i, _), v in zip(batch, vecs)],
        template="(%s, %s, %s::real[])",
    )


def embed_bucket(bid: str, retriever: str, docs: bool = False) -> None:
    spec = RETRIEVERS[vector_name(retriever)]
    table, key, col = ("documents", "filename", "description") if docs else ("chunks", "chunk_id", "text")
    try:
        with db() as conn, conn.cursor() as cur:
            cur.execute(f"SELECT {key}, {col} FROM {table} WHERE bucket_id = %s ORDER BY {key}", (bid,))
            rows = cur.fetchall()
        model = embedder(retriever)
        for i in range(0, len(rows), BATCH):
            batch = rows[i:i + BATCH]
            vecs = model.encode([spec["passage"] + t for _, t in batch], normalize_embeddings=True)
            with db() as conn, conn.cursor() as cur:
                write_vectors(cur, table, key, bid, batch, vecs)
                cur.execute("UPDATE buckets SET embedded_count = %s WHERE id = %s", (i + len(batch), bid))
                conn.commit()
        with db() as conn, conn.cursor() as cur:
            cur.execute("UPDATE buckets SET status = 'ready', indexed_at = NOW() WHERE id = %s", (bid,))
            conn.commit()
        print(f"bucket {bid} ready: {len(rows)} vectors ({retriever})")
    except Exception as e:  # keep the row so the UI can show what went wrong
        print(f"bucket {bid} failed: {e}")
        with db() as conn, conn.cursor() as cur:
            cur.execute("UPDATE buckets SET status = 'error', error = %s WHERE id = %s", (str(e)[:500], bid))
            conn.commit()


@app.post("/api/buckets/import", status_code=201)
async def import_zip(bg: BackgroundTasks, file: UploadFile = File(...), retriever: str = Form(...)):
    """One step: the chunker's bucket.zip + a retriever. Named `<chunker> · <retriever>`."""
    if retriever not in RETRIEVERS:
        raise HTTPException(400, f"unknown retriever; choose one of {list(RETRIEVERS)}")
    try:
        z = zipfile.ZipFile(io.BytesIO(await file.read()))
        corpus, answers = z.read("corpus.parquet"), z.read("answers.parquet")
        chunker = json.loads(z.read("manifest.json"))["config"]
    except (zipfile.BadZipFile, KeyError, ValueError) as e:
        raise HTTPException(400, f"not a chunker bucket.zip (corpus.parquet + answers.parquet + manifest.json): {e}")
    with db() as conn, cursor(conn) as cur:
        cur.execute("INSERT INTO buckets (id, name, chunker) VALUES (%s, %s, %s) RETURNING id",
                    (uuid.uuid4().hex[:8], f"{chunker['name']} · {retriever}", Json(chunker)))
        bid = cur.fetchone()["id"]
        conn.commit()
    try:
        return ingest(bid, bg, corpus, answers, retriever)
    except HTTPException:  # bad parquet: don't leave an empty bucket behind
        with db() as conn, conn.cursor() as cur:
            cur.execute("DELETE FROM buckets WHERE id = %s", (bid,))
            conn.commit()
        raise


@app.post("/api/buckets/{bid}/upload")
async def upload(bid: str, bg: BackgroundTasks, file: UploadFile = File(...),
                 answers: UploadFile = File(...), retriever: str = Form(...)):
    if retriever not in RETRIEVERS:
        raise HTTPException(400, f"unknown retriever; choose one of {list(RETRIEVERS)}")
    return ingest(bid, bg, await file.read(), await answers.read(), retriever)


def ingest(bid: str, bg: BackgroundTasks, raw: bytes, answers_raw: bytes, retriever: str) -> dict:
    df = read_parquet(raw, "corpus", REQUIRED_COLUMNS)
    if "heading" not in df.columns:
        df["heading"] = ""
    rows = [
        (bid, str(r.chunk_id), str(r.filename), int(r.chunk_index),
         Json([int(p) for p in r.pages]), str(r.heading or ""), str(r.text))
        for r in df.itertuples()
    ]

    ans = read_parquet(answers_raw, "answers", ANSWER_COLUMNS)
    if "part" not in ans.columns:
        ans["part"] = 0
    if "coverage" not in ans.columns:
        ans["coverage"] = None
    known = {r[1] for r in rows}
    unknown = sorted(set(map(str, ans.chunk_id)) - known)
    if unknown:
        raise HTTPException(400, f"answers reference {len(unknown)} chunk_id(s) not in corpus, "
                                 f"e.g. {unknown[:3]} — wrong pair of files?")
    qrels = [(bid, str(a.query_id), str(a.chunk_id), int(a.part),
              None if pd.isna(a.coverage) else float(a.coverage)) for a in ans.itertuples()]

    is_bm25 = RETRIEVERS[retriever]["kind"] == "bm25"
    forget_bm25(bid)

    with db() as conn, cursor(conn) as cur:
        b = get_bucket(cur, bid)
        # A bucket is written once. Its id is the stable handle of one (corpus,
        # retriever); swapping either would silently invalidate every result
        # recorded against it. Want a different corpus? Create another bucket.
        if b["kind"] != "chunks":
            raise HTTPException(409, "not a chunks bucket")
        if b["status"] not in ("empty", "error"):
            raise HTTPException(409, f"bucket is {b['status']}: buckets are immutable once indexed, create a new one")
        cur.execute("DELETE FROM chunks WHERE bucket_id = %s", (bid,))  # leftovers from a failed attempt
        cur.execute("DELETE FROM qrels WHERE bucket_id = %s", (bid,))
        execute_values(
            cur,
            "INSERT INTO chunks (bucket_id, chunk_id, filename, chunk_index, pages, heading, text) VALUES %s",
            rows,
        )
        execute_values(
            cur,
            "INSERT INTO qrels (bucket_id, query_id, chunk_id, part, coverage) VALUES %s "
            "ON CONFLICT DO NOTHING",
            qrels,
        )
        cur.execute("""
            UPDATE buckets SET retriever = %s, status = %s, chunk_count = %s, embedded_count = %s,
                   parquet_sha = %s, error = NULL, indexed_at = CASE WHEN %s THEN NOW() END
            WHERE id = %s
        """, (retriever, "ready" if is_bm25 else "indexing", len(rows),
              len(rows) if is_bm25 else 0, hashlib.sha256(raw).hexdigest(), is_bm25, bid))
        conn.commit()
        b = get_bucket(cur, bid)
    if not is_bm25:
        bg.add_task(embed_bucket, bid, retriever)
    return present(b)


@app.post("/api/buckets/descriptions", status_code=201)
async def import_descriptions(bg: BackgroundTasks, file: UploadFile = File(...), retriever: str = Form(...)):
    """A descriptions bucket: description.parquet (filename, description) + its own retriever.
    Search it alone to see which documents a question lands on, or use it as
    layer 1 of any chunks bucket: /api/buckets/<chunks>/search?docs=<this id>."""
    if retriever not in RETRIEVERS:
        raise HTTPException(400, f"unknown retriever; choose one of {list(RETRIEVERS)}")
    raw = await file.read()
    desc = read_parquet(raw, "description", DESCRIPTION_COLUMNS)
    is_bm25 = RETRIEVERS[retriever]["kind"] == "bm25"
    with db() as conn, cursor(conn) as cur:
        bid = uuid.uuid4().hex[:8]
        cur.execute("""
            INSERT INTO buckets (id, name, kind, retriever, status, chunk_count, embedded_count, parquet_sha, indexed_at)
            VALUES (%s, %s, 'descriptions', %s, %s, %s, %s, %s, CASE WHEN %s THEN NOW() END)
        """, (bid, f"descrições · {retriever}", retriever, "ready" if is_bm25 else "indexing", len(desc),
              len(desc) if is_bm25 else 0, hashlib.sha256(raw).hexdigest(), is_bm25))
        execute_values(cur, "INSERT INTO documents (bucket_id, filename, description) VALUES %s "
                            "ON CONFLICT DO NOTHING",
                       [(bid, str(d.filename), str(d.description)) for d in desc.itertuples()])
        conn.commit()
        b = get_bucket(cur, bid)
    if not is_bm25:
        bg.add_task(embed_bucket, bid, retriever, True)
    return present(b)


# ── browse ─────────────────────────────────────────────────────────────────

@app.get("/api/buckets/{bid}/answers")
def list_answers(bid: str):
    """The gabarito: one row per (query, chunk). Same shape as dataset's answers.parquet."""
    with db() as conn, cursor(conn) as cur:
        get_bucket(cur, bid)
        cur.execute("SELECT query_id, chunk_id, part, coverage FROM qrels WHERE bucket_id = %s "
                    "ORDER BY query_id, part, chunk_id", (bid,))
        return list(cur.fetchall())


@app.get("/api/buckets/{bid}/documents")
def list_documents(bid: str):
    with db() as conn, cursor(conn) as cur:
        if get_bucket(cur, bid)["kind"] == "descriptions":
            cur.execute("SELECT filename, 1 AS chunk_count FROM documents WHERE bucket_id = %s ORDER BY filename",
                        (bid,))
            return list(cur.fetchall())
        cur.execute("""
            SELECT filename, COUNT(*)::int AS chunk_count
            FROM chunks WHERE bucket_id = %s GROUP BY filename ORDER BY filename
        """, (bid,))
        return list(cur.fetchall())


@app.get("/api/buckets/{bid}/documents/{filename}/chunks")
def document_chunks(bid: str, filename: str):
    with db() as conn, cursor(conn) as cur:
        cur.execute("""
            SELECT chunk_id AS id, chunk_index, text, heading, pages, embedding
            FROM chunks WHERE bucket_id = %s AND filename = %s
            UNION ALL
            SELECT filename, 0, description, 'descrição', '[]'::jsonb, embedding
            FROM documents WHERE bucket_id = %s AND filename = %s
            ORDER BY chunk_index
        """, (bid, filename, bid, filename))
        rows = cur.fetchall()
        for r in rows:
            if r["embedding"] is not None:
                r["embedding"] = r["embedding"].to_list()  # pgvector Vector, not numpy
        return rows


# ── search ─────────────────────────────────────────────────────────────────

BM25_SOURCES = {
    # a chunks bucket's chunks (layer 2, or a single layer)
    "chunks": "SELECT chunk_id AS id, filename, heading, text FROM chunks WHERE bucket_id = %s ORDER BY chunk_id",
    # a descriptions bucket's summaries (layer 1)
    "descriptions": "SELECT filename AS id, filename, '' AS heading, description AS text FROM documents "
                    "WHERE bucket_id = %s ORDER BY filename",
}


def forget_bm25(bid: str) -> None:
    for source in BM25_SOURCES:
        _bm25.pop((bid, source), None)


def bm25_index(cur, bid: str, source: str = "chunks"):
    """BM25 over one of BM25_SOURCES of bucket bid. ids are chunk_ids, or filenames for descriptions."""
    if (bid, source) not in _bm25:
        import rank_bm25
        cur.execute(BM25_SOURCES[source], (bid,))
        rows = cur.fetchall()
        # The heading goes in with the text: a section title naming the query term is strong evidence.
        texts = [f"{r['heading'] or ''}\n{r['text']}" for r in rows]
        index = getattr(rank_bm25, f"BM25{BM25_VARIANT}")([tokenize(t) for t in texts], k1=BM25_K1, b=BM25_B)
        _bm25[(bid, source)] = (index, [r["id"] for r in rows], [r["filename"] for r in rows], mine_acronyms(texts))
    return _bm25[(bid, source)]


def bm25_rank(cur, bid: str, q: str, k: int, files: list[str] | None = None,
              source: str = "chunks") -> list[tuple[str, float]]:
    bm25, ids, filenames, acronyms = bm25_index(cur, bid, source)
    tokens = expand_query(tokenize(q), acronyms)
    if not tokens:
        return []
    scores = bm25.get_scores(tokens)
    order = sorted(range(len(ids)), key=lambda i: scores[i], reverse=True)
    # a chunk sharing no term with the query is not a result (BM25Plus scores those > 0).
    # Scores stay corpus-wide; files= only filters, so IDF is the same with or without layer 1.
    terms = set(tokens)
    hits = (i for i in order if not terms.isdisjoint(bm25.doc_freqs[i])
            and (files is None or filenames[i] in files))
    return [(ids[i], float(scores[i])) for i in itertools.islice(hits, k)]


@functools.lru_cache(maxsize=256)
def embed_query(retriever: str, q: str) -> list[float]:
    """Cached: layer 1 and layer 2 embed the same question."""
    spec = RETRIEVERS[vector_name(retriever)]
    return embedder(retriever).encode(spec["query"] + q, normalize_embeddings=True).tolist()


def vector_rank(cur, bid: str, retriever: str, q: str, k: int, files: list[str] | None = None,
                docs: bool = False) -> list[tuple[str, float]]:
    vec = embed_query(retriever, q)
    table, key = ("documents", "filename") if docs else ("chunks", "chunk_id")
    cur.execute(f"""
        SELECT {key} AS id, (1 - (embedding <=> %s::vector))::float AS similarity
        FROM {table} WHERE bucket_id = %s AND embedding IS NOT NULL
          AND (%s::text[] IS NULL OR filename = ANY(%s::text[]))
        ORDER BY embedding <=> %s::vector LIMIT %s
    """, (vec, bid, files, files, vec, k))
    return [(r["id"], r["similarity"]) for r in cur.fetchall()]


def rrf(*rankings: list[tuple[str, float]], k: int = RRF_K,
        weights: tuple[float, ...] = ()) -> list[tuple[str, float]]:
    """Reciprocal Rank Fusion: score(d) = sum over rankers of w / (k + rank_d)."""
    fused: dict[str, float] = {}
    for n, ranking in enumerate(rankings):
        w = weights[n] if n < len(weights) else 1.0
        for pos, (cid, _) in enumerate(ranking, start=1):
            fused[cid] = fused.get(cid, 0.0) + w / (k + pos)
    return sorted(fused.items(), key=lambda x: x[1], reverse=True)


def rerank(cur, bid: str, name: str, q: str, ranked: list[tuple[str, float]]) -> list[tuple[str, float]]:
    """Rescore candidates with a cross-encoder: one forward pass per (query, chunk)."""
    if not ranked:
        return []
    ids = [c for c, _ in ranked]
    cur.execute("SELECT chunk_id, heading, text FROM chunks WHERE bucket_id = %s AND chunk_id = ANY(%s)",
                (bid, ids))
    texts = {r["chunk_id"]: f"{r['heading'] or ''}\n{r['text']}".strip() for r in cur.fetchall()}
    scores = reranker(name).predict([(q, texts[c]) for c in ids])
    return sorted(zip(ids, map(float, scores)), key=lambda x: x[1], reverse=True)


def rewrite(q: str, n: int) -> tuple[str, ...]:
    """The first n pre-generated rewrites of q (gen_rewrites.py). No LLM call at search time."""
    if q not in REWRITES:
        raise HTTPException(404, "no pre-generated rewrites for this question; run gen_rewrites.py")
    return tuple(REWRITES[q][:n])


def rank_one(cur, b: dict, q: str, k: int, files: list[str] | None = None,
             docs: bool = False) -> list[tuple[str, float]]:
    """One layer with b's retriever: chunks (optionally only of `files`), or (docs) descriptions."""
    source = "descriptions" if docs else "chunks"
    kind = RETRIEVERS[b["retriever"]]["kind"]
    if kind == "bm25":
        return bm25_rank(cur, b["id"], q, k, files, source)
    if kind == "vector":
        return vector_rank(cur, b["id"], b["retriever"], q, k, files, docs)
    return rrf(bm25_rank(cur, b["id"], q, RRF_DEPTH, files, source),
               vector_rank(cur, b["id"], b["retriever"], q, RRF_DEPTH, files, docs),
               weights=(RRF_BM25_WEIGHT, 1.0))[:k]


def pick_documents(cur, d: dict | None, q: str, doc_top: int) -> list[str] | None:
    """Layer 1: the doc_top filenames whose descriptions (descriptions bucket d, its retriever)
    best match q. No d = search all."""
    if not d:
        return None
    return [f for f, _ in rank_one(cur, d, q, doc_top, docs=True)]


def rank(cur, b: dict, q: str, k: int, d: dict | None = None, doc_top: int = DOC_TOP) -> list[tuple[str, float]]:
    """A descriptions bucket ranks its documents. A chunks bucket: layer 1 (if d) then layer 2,
    per query, so each rewrite picks its own documents."""
    if b["kind"] == "descriptions":
        return rank_one(cur, b, q, k, docs=True)
    return rank_one(cur, b, q, k, files=pick_documents(cur, d, q, doc_top))


def retrieve(cur, b: dict, queries: list[str], k: int, rerank_with: str | None = None,
             d: dict | None = None, doc_top: int = DOC_TOP) -> list[tuple[str, float]]:
    """queries[0] is the user's question, the rest its rewrites. One query: the
    plain ranking. Several: each is ranked RRF_DEPTH deep and the rankings fused.
    The reranker always reads the original question."""
    depth = max(k, RERANK_DEPTH) if rerank_with else k
    if len(queries) == 1:
        ranked = rank(cur, b, queries[0], depth, d, doc_top)
    else:
        ranked = rrf(*(rank(cur, b, x, max(depth, RRF_DEPTH), d, doc_top) for x in queries))[:depth]
    if rerank_with:
        ranked = rerank(cur, b["id"], rerank_with, queries[0], ranked)[:k]
    return ranked


def descriptions_for(cur, b: dict, docs: str) -> dict:
    """The descriptions bucket `docs`, checked against chunks bucket b."""
    d = get_bucket(cur, docs)
    if d["kind"] != "descriptions":
        raise HTTPException(400, f"docs={docs} is a {d['kind']} bucket, not descriptions")
    if d["status"] != "ready":
        raise HTTPException(409, f"descriptions bucket is {d['status']}")
    # A file with no description never passes layer 1: its chunks would be silently unreachable.
    cur.execute("SELECT DISTINCT filename FROM chunks WHERE bucket_id = %s "
                "EXCEPT SELECT filename FROM documents WHERE bucket_id = %s", (b["id"], d["id"]))
    missing = sorted(r["filename"] for r in cur.fetchall())
    if missing:
        raise HTTPException(400, f"descriptions bucket {docs} misses {len(missing)} file(s) of this bucket, "
                                 f"e.g. {missing[:3]}")
    return d


def do_search(cur, b: dict, q: str, k: int, rerank_with: str | None = None, variants: int = 0,
              docs: str | None = None, doc_top: int = DOC_TOP) -> dict:
    if b["status"] != "ready":
        raise HTTPException(409, f"bucket is {b['status']}")
    if rerank_with and rerank_with not in RERANKERS:
        raise HTTPException(400, f"unknown reranker; choose one of {list(RERANKERS)}")
    if b["kind"] == "descriptions" and (rerank_with or docs):
        raise HTTPException(400, "a descriptions bucket takes neither rerank nor docs")
    d = descriptions_for(cur, b, docs) if docs else None
    queries = [q, *rewrite(q, variants)] if variants else [q]
    ranked = retrieve(cur, b, queries, k, rerank_with, d, doc_top)
    out = {"query": q, "k": k, "bucket": b["id"], "retriever": b["retriever"],
           "rerank": rerank_with, "variants": variants, "queries": queries,
           "docs": docs, "doc_top": doc_top if d else None,
           "documents": pick_documents(cur, d, q, doc_top), "results": []}  # layer 1 of the original question
    if ranked and b["kind"] == "descriptions":
        cur.execute("SELECT filename AS id, 0 AS chunk_index, description AS text, '' AS heading, "
                    "'[]'::jsonb AS pages, filename FROM documents WHERE bucket_id = %s AND filename = ANY(%s)",
                    (b["id"], [c for c, _ in ranked]))
        by_id = {r["id"]: r for r in cur.fetchall()}
        out["results"] = [{**by_id[c], "similarity": s} for c, s in ranked if c in by_id]
    elif ranked:
        cur.execute("""
            SELECT chunk_id AS id, chunk_index, text, heading, pages, filename
            FROM chunks WHERE bucket_id = %s AND chunk_id = ANY(%s)
        """, (b["id"], [c for c, _ in ranked]))
        by_id = {r["id"]: r for r in cur.fetchall()}
        out["results"] = [{**by_id[c], "similarity": s} for c, s in ranked if c in by_id]
    return out


@app.get("/api/buckets/{bid}/search")
def bucket_search(bid: str, q: str = Query(..., min_length=1), k: int = Query(5, ge=1, le=50),
                  rerank: str | None = None, variants: int = Query(0, ge=0, le=MAX_VARIANTS),
                  docs: str | None = None, doc_top: int = Query(DOC_TOP, ge=1, le=50)):
    with db() as conn, cursor(conn) as cur:
        return do_search(cur, get_bucket(cur, bid), q, k, rerank, variants, docs, doc_top)


def default_bucket(cur) -> dict | None:
    cur.execute(BUCKET_SQL + " WHERE b.status = 'ready' AND b.kind = 'chunks' ORDER BY b.indexed_at DESC NULLS LAST LIMIT 1")
    return cur.fetchone()


@app.get("/api/search")
def search(q: str = Query(..., min_length=1), k: int = Query(5, ge=1, le=50),
           bucket: str | None = None, rerank: str | None = None,
           variants: int = Query(0, ge=0, le=MAX_VARIANTS),
           docs: str | None = None, doc_top: int = Query(DOC_TOP, ge=1, le=50)):
    """Alias for eval/: same shape as week01/week03. Default = last indexed bucket."""
    with db() as conn, cursor(conn) as cur:
        b = get_bucket(cur, bucket) if bucket else default_bucket(cur)
        if not b:
            raise HTTPException(404, "no ready bucket")
        return do_search(cur, b, q, k, rerank, variants, docs, doc_top)


@app.get("/api/health")
def health():
    with db() as conn, cursor(conn) as cur:
        b = default_bucket(cur)
    # `embedding_model` is what eval/ records per run.
    model = f"{RETRIEVERS[b['retriever']]['model']} @ {b['name']} ({b['id']})" if b else None
    return {
        "status": "ok",
        "embedding_model": model,
        "default_bucket": present(b) if b else None,
        "retrievers": {k: v["model"] for k, v in RETRIEVERS.items()},
        "rerankers": RERANKERS,
        # eval/ offers ?variants= only when this is present
        "two_layer": {"doc_top": DOC_TOP},  # eval/ offers ?docs= only when this is present
        "transform": {"model": TRANSFORM_MODEL, "max_variants": MAX_VARIANTS,
                      "questions": len(REWRITES)} if REWRITES else None,
    }


if __name__ == "__main__":  # python main.py: self-check for the fusion, no DB needed
    a = [("x", 9.0), ("y", 8.0), ("z", 1.0)]
    v = [("y", 0.9), ("w", 0.8), ("x", 0.7)]
    ids = [c for c, _ in rrf(a, v)]
    assert ids[0] == "y" and set(ids[:2]) == {"x", "y"} and ids[-1] == "z", ids
    assert rrf([], []) == [] and rrf(a, []) == rrf(a)
    assert "hybrid-bge-m3" in RETRIEVERS and vector_name("hybrid-bge-m3") == "bge-m3"
    assert [c for c, _ in rrf(a, v, weights=(10.0, 1.0))][:3] == ["x", "y", "z"]  # bm25 order wins

    # rerankers are a search option, not retrievers
    assert not any("+" in r for r in RETRIEVERS) and set(RERANKERS) == {"mminilm-rerank", "bge-reranker", "mxbai-rerank"}

    # tokenizer: stems, accents, whole references
    assert tokenize("Decisão decisões decisao") == ["decis"] * 3
    assert tokenize("Lei 8.666/93") == tokenize("lei 8666/93") == ["lei", "8666/93"]
    assert tokenize("o artigo.O prazo") == tokenize("o artigo. O prazo")

    # acronyms: mined from the corpus, expanded both ways at query time
    acr = mine_acronyms(["O Código de Trânsito Brasileiro (CTB) diz.", "Ver a (XYZ) e (ABC)."])
    assert acr == {"ctb": tokenize("Código de Trânsito Brasileiro")}, acr
    assert set(expand_query(tokenize("o que diz o CTB"), acr)) >= set(tokenize("codigo transito"))
    assert "ctb" in expand_query(tokenize("código de trânsito brasileiro"), acr)
    # two layers: bm25 filtered to the chosen files, scores unchanged
    import rank_bm25
    texts = ["multa de trânsito", "multa ambiental", "animais comunitários"]
    _bm25[("t", "chunks")] = (rank_bm25.BM25Okapi([tokenize(t) for t in texts]), ["c1", "c2", "c3"],
                           ["a.pdf", "b.pdf", "c.pdf"], {})
    assert [c for c, _ in bm25_rank(None, "t", "multa", 5)] in (["c1", "c2"], ["c2", "c1"])
    assert [c for c, _ in bm25_rank(None, "t", "multa", 5, files=["b.pdf"])] == ["c2"]
    # layer 1 (descriptions bucket d) picks the files layer 2 searches; no d = no filter
    calls = []
    real_rank_one = rank_one
    rank_one = lambda cur, b, x, k, files=None, docs=False: (  # noqa: E731
        calls.append((b["id"], k, docs, files)) or ([("a.pdf", 1.0), ("b.pdf", 0.5)] if docs else [("c1", 1.0)]))
    chunks_b, desc_b = {"id": "c", "kind": "chunks"}, {"id": "d", "kind": "descriptions"}
    assert rank(None, chunks_b, "q", 5, desc_b, 2) == [("c1", 1.0)]
    assert calls == [("d", 2, True, None), ("c", 5, False, ["a.pdf", "b.pdf"])], calls
    calls.clear()
    rank(None, chunks_b, "q", 5)
    assert calls == [("c", 5, False, None)], calls
    calls.clear()
    rank(None, desc_b, "q", 5)                       # searched alone: ranks documents
    assert calls == [("d", 5, True, None)], calls
    rank_one = real_rank_one

    # query transformation: rewrites fused by RRF, rerank reads the original
    fake = {"q": [("a", 1.0), ("b", 0.9)], "q1": [("c", 1.0), ("b", 0.9)], "q2": [("b", 1.0)]}
    rank = lambda cur, b, x, k, *a: fake[x][:k]  # noqa: E731
    assert retrieve(None, {}, ["q"], 5) == fake["q"]                        # no variants: untouched
    assert [c for c, _ in retrieve(None, {}, ["q", "q1", "q2"], 2)] == ["b", "a"]  # b is in all three
    seen = []
    rerank = lambda cur, bid, name, x, ranked: seen.append(x) or ranked[::-1]  # noqa: E731
    assert [c for c, _ in retrieve(None, {"id": "x"}, ["q", "q1"], 1, "r")] and seen == ["q"]
    print("ok")
